controller/EncryptionApi.php, manifest.php, model/Service/KeyProvider/FileKeyProviderService.php, model/Service/Result/DecryptResultService.php, model/Service/Result/EncryptResultService.php, model/Service/Session/EncryptedUser.php, model/Service/SessionState/EncryptedStateStorage.php, model/Service/Sync/EncryptRdfDeliverySyncFormatter.php, model/Service/Sync/EncryptUserSyncFormatter.php, model/Service/User/EncryptedUserFactoryService.php, scripts/update/Updater.php, test/Service/DeliveryMonitoring/EncryptedMonitoringServiceTest.php, test/Service/EncryptionSymmetricServiceTest.php, test/Service/FileSystem/EncryptionFlyWrapperTest.php, test/Service/KeyProvider/AsymmetricKeyPairProviderServiceTest.php, test/Service/KeyProvider/DummyKeyProviderTest.php, test/Service/KeyProvider/FileKeyProviderServiceTest.php, test/Service/KeyProvider/KeyProviderClientTest.php, test/Service/KeyProvider/SimpleKeyProviderServiceTest.php, test/Service/Result/DecryptResultServiceTest.php, test/Service/Result/EncryptResultServiceTest.php, test/Service/Result/SyncEncryptedResultServiceTest.php, test/Service/Session/EncryptedUserTest.php, test/Service/SessionState/EncryptedStateStorageTest.php, test/Service/Sync/EncryptRdfDeliverySyncFormatterTest.php, test/Service/Sync/EncryptUserSyncFormatterTest.php, test/Service/User/EncryptedUserFactoryServiceTest.php, test/Service/User/UserHandlerKeysTest.php
=> Release 0.6.2

composer.json, manifest.php, model/Model/Asymmetric/AsymmetricRSAKeyPairProvider.php, model/Service/KeyProvider/FileKeyProviderService.php, scripts/tools/SetupUserApplicationKey.php, scripts/update/Updater.php, test/Model/AsymmetricRSAKeyPairProviderTest.php, test/Service/KeyProvider/AsymmetricKeyPairProviderServiceTest.php, test/Service/KeyProvider/FileKeyProviderServiceTest.php
Remove file system league dependency
=> Release 0.7.1

manifest.php, model/Service/Session/EncryptedUser.php, scripts/update/Updater.php
=> Fix/tao 6250/fix some sync issue

manifest.php, model/Service/Mapper/TestSessionSyncMapper.php, model/Service/Result/DecryptResultService.php, model/Service/TestSession/EncryptSyncTestSessionService.php, scripts/install/RegisterTestSessionSyncMapper.php, scripts/tools/SetupSyncTestSessionService.php, scripts/update/Updater.php
=> Release 0.12.0

manifest.php, model/Service/Lti/EncryptFactoryLtiAuthAdapterService.php, model/Service/Lti/EncryptLtiAuthAdapter.php, model/Service/Session/EncryptedLtiUser.php, scripts/tools/SetupEncryptFactoryLtiAuthAdapterService.php, scripts/update/Updater.php, test/Service/Lti/EncryptFactoryLtiAuthAdapterServiceTest.php, test/Service/Session/EncryptedLtiUserTest.php, test/integration/Service/Lti/EncryptLtiAuthAdapterTest.php
=> Release 0.16.0

manifest.php, model/Service/Session/EncryptedLtiUser.php, scripts/update/Updater.php
=> Release 0.16.1

manifest.php, model/Event/ProctorCreatedHandler.php, scripts/update/Updater.php
=> Release 1.0.0

manifest.php, model/Model/FileSystem/EncryptionAdapter.php, model/Model/Symmetric/Symmetric.php, model/Service/Algorithm/AlgorithmSymmetricService.php, model/Service/Algorithm/AlgorithmSymmetricServiceInterface.php, model/Service/EncryptionSymmetricService.php, model/Service/FileSystem/EncryptionFlyWrapper.php, model/Service/Lti/LaunchData/Validator/LtiCustomerAppKeyValidator.php, model/Service/Session/EncryptedLtiUser.php, scripts/tools/SetupLtiCustomerAppKeyValidator.php, scripts/tools/SetupPhpCompilationCacheOff.php, scripts/update/Updater.php, test/Model/SymmetricTest.php, test/Service/DeliveryMonitoring/EncryptedMonitoringServiceTest.php, test/Service/FileSystem/EncryptionFlyWrapperTest.php, test/Service/Session/EncryptedLtiUserTest.php, test/Service/Session/EncryptedUserTest.php
=> Release 1.1.0

manifest.php, model/Service/DeliveryMonitoring/EncryptedLtiMonitoringService.php, scripts/update/Updater.php
=> Release 1.2.1

manifest.php, model/Service/Result/DecryptResultService.php, model/Service/TestSession/EncryptSyncTestSessionService.php, scripts/update/Updater.php
=> Release 1.2.2

manifest.php, model/Service/Result/SyncEncryptedResultService.php, scripts/update/Updater.php, test/Service/Result/SyncEncryptedResultServiceTest.php
Collect logs about import of encrypted delivery executions results on the central server.
Depends on https://github.com/oat-sa/extension-tao-sync/pull/88
=> Feature/tao 7191/collect synchronization logs on central server

manifest.php, model/Service/Result/SyncEncryptedResultService.php, scripts/update/Updater.php, test/Service/Result/SyncEncryptedResultServiceTest.php
=> Release 2.0.0

manifest.php, model/Service/Session/EncryptedLtiUser.php, scripts/update/Updater.php
=> Release 2.0.1

manifest.php, model/Service/Result/DecryptResultService.php, model/Service/Result/StoreVariableService.php, model/Service/Result/StoreVariableServiceInterface.php, model/Service/Result/SyncEncryptedResultService.php, scripts/update/Updater.php
=> Release 3.0.0

manifest.php, model/Service/Result/SyncEncryptedResultDataFormatter.php, model/Service/Result/SyncEncryptedResultService.php, scripts/tools/SetupEncryptedSyncResult.php, scripts/update/Updater.php
=> Release 3.1.0

manifest.php, model/Service/DeliveryAssembly/EncryptedAssemblerFactory.php, model/Service/DeliveryAssembly/EncryptedAssemblerService.php, model/Service/EncryptionAwareInterface.php, model/Service/EncryptionServiceFactory.php, scripts/tools/DeliveryAssembly/ExportEncryptedAssembly.php, scripts/update/Updater.php
=> Release 3.2.0

manifest.php, model/Service/Lti/EncryptLtiUserFactoryService.php, scripts/update/Updater.php
=> Release 3.2.2

manifest.php, scripts/update/Updater.php, test/Service/DeliveryLog/DecryptDeliveryLogFormatterServiceTest.php, test/Service/DeliveryMonitoring/EncryptedMonitoringServiceTest.php, test/Service/EncryptionSymmetricServiceTest.php, test/Service/FileSystem/EncryptionFlyWrapperTest.php, test/Service/KeyProvider/DummyKeyProviderTest.php, test/Service/KeyProvider/FileKeyProviderServiceTest.php, test/Service/KeyProvider/KeyProviderClientTest.php, test/Service/KeyProvider/SimpleKeyProviderServiceTest.php, test/Service/LtiConsumer/EncryptLtiConsumerFormatterServiceTest.php, test/Service/Result/DecryptResultServiceTest.php, test/Service/Result/SyncEncryptedResultServiceTest.php, test/Service/Session/EncryptedUserTest.php, test/Service/SessionState/EncryptedStateStorageTest.php, test/Service/Sync/EncryptRdfDeliverySyncFormatterTest.php, test/Service/Sync/EncryptUserSyncFormatterTest.php, test/Service/User/EncryptedUserFactoryServiceTest.php, test/Service/User/UserHandlerKeysTest.php
=> Release 4.0.0

composer.json, manifest.php, scripts/update/Updater.php
=> Release 5.0.1

manifest.php, scripts/update/Updater.php, test/Model/AlgorithmFactoryTest.php, test/Model/AsymmetricRSATest.php, test/Model/SymmetricTest.php, test/Service/Algorithm/AlgorithmAsymmetricRSAServiceTest.php, test/Service/Algorithm/AlgorithmSymmetricServiceTest.php, test/Service/DeliveryLog/DecryptDeliveryLogFormatterServiceTest.php, test/Service/KeyProvider/FileKeyProviderServiceTest.php, test/Service/KeyProvider/KeyProviderClientTest.php, test/Service/LtiConsumer/EncryptLtiConsumerFormatterServiceTest.php, test/Service/Result/SyncEncryptedResultServiceTest.php, test/Service/Session/EncryptedUserTest.php, test/Service/SessionState/EncryptedStateStorageTest.php, test/Service/Sync/EncryptRdfDeliverySyncFormatterTest.php, test/Service/Sync/EncryptUserSyncFormatterTest.php, test/Service/User/EncryptedUserFactoryServiceTest.php, test/Service/User/UserHandlerKeysTest.php, test/unit/model/Service/DeliveryAssembly/EncryptedAssemblyFilesReaderDecoratorTest.php
related to: https://oat-sa.atlassian.net/browse/TDR-1
depends on: https://github.com/oat-sa/generis/pull/751
Upgrade to phpunit8
=> Feature/tdr 1/phpunit8 upgrade

manifest.php, scripts/update/Updater.php, test/Model/AlgorithmFactoryTest.php, test/Model/AsymmetricRSATest.php, test/Model/SymmetricTest.php, test/Service/Algorithm/AlgorithmAsymmetricRSAServiceTest.php, test/Service/Algorithm/AlgorithmSymmetricServiceTest.php, test/Service/DeliveryLog/DecryptDeliveryLogFormatterServiceTest.php, test/Service/KeyProvider/FileKeyProviderServiceTest.php, test/Service/KeyProvider/KeyProviderClientTest.php, test/Service/LtiConsumer/EncryptLtiConsumerFormatterServiceTest.php, test/Service/Result/SyncEncryptedResultServiceTest.php, test/Service/Session/EncryptedUserTest.php, test/Service/SessionState/EncryptedStateStorageTest.php, test/Service/Sync/EncryptRdfDeliverySyncFormatterTest.php, test/Service/Sync/EncryptUserSyncFormatterTest.php, test/Service/User/EncryptedUserFactoryServiceTest.php, test/Service/User/UserHandlerKeysTest.php, test/unit/model/Service/DeliveryAssembly/EncryptedAssemblyFilesReaderDecoratorTest.php
=> Release 5.1.0

manifest.php, model/Service/Result/EncryptResultService.php, scripts/update/Updater.php, test/Service/Result/EncryptResultServiceTest.php
see: https://github.com/oat-sa/extension-tao-delivery-rdf/pull/317
=> move DetectTestAndItemIdentifiersHelper to taoSync extension

manifest.php, model/Service/Result/EncryptResultService.php, scripts/update/Updater.php, test/Service/Result/EncryptResultServiceTest.php
=> Release 5.2.0

model/Service/Result/DecryptResultService.php, model/Service/Result/SyncEncryptedResultService.php, model/Task/DecryptDeliveryExecutionTask.php
=> Release 6.1.0

model/Service/DeliveryMonitoring/EncryptedLtiMonitoringService.php, model/Service/DeliveryMonitoring/EncryptedMonitoringService.php
=> Release 6.1.1
